### PR TITLE
test : increase step coverage

### PR DESCRIPTION
**Pull request by shubham-cmyk**
Fix : https://github.com/kyverno/chainsaw/issues/337

### CODE REVIEW

**Comment by eddycharly** [comment]
@shubham-cmyk not that simple ;-)

**Comment by shubham-cmyk** [comment]
> @shubham-cmyk not that simple ;-)

Do i need to get to the TestParse now

**Comment by eddycharly** [comment]
@shubham-cmyk you get that coverage did not change at all right ?

**Comment by shubham-cmyk** [comment]
Right it didn't changed i looked at that

**Pull request closed without merging**
