### PR TITLE
feat: add get collector

### LINKED ISSUE #887: [Feature] Create a get collector
### Problem Statement

We lack a get collector today.

### Solution Description

Create a get collector (similar to describe).

### Alternatives

_No response_

### Additional Context

_No response_

### Slack discussion

_No response_

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

### PR DESCRIPTION
**Pull request by Chandan-DK**
## Explanation
Add get collector

## Related issue
Fixes #887 

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ ] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
- [ ] This is a bug fix and I have added unit tests that prove my fix is effective.

### CODE REVIEW

**Comment by eddycharly** [comment]
Thanks @Chandan-DK !

Can you add validation too ? (similar to validation for other collectors)

**Comment by eddycharly** [comment]
One more request, i would love to see some unit tests too :)

**Comment by Chandan-DK** [comment]
> One more request, i would love to see some unit tests too :)

Sure!

**Comment by eddycharly** [comment]
@Chandan-DK run `make codegen` and commit the changes

**Pull request merged**
