### PR TITLE
chore: refactor operations docs

### PR DESCRIPTION
**Pull request by eddycharly**
Refactor operations docs.

### CODE REVIEW

**Comment by shubham-cmyk** [comment]
@eddycharly  but the test failed here.

**Comment by eddycharly** [comment]
yeah, will fix in follow up

**Comment by shubham-cmyk** [comment]
```
            	            	expected: []string{"ASSERT: [RUNNING...]", "ASSERT: [ERROR\nresource test-pod doesn't match expectation:\n    spec.containers[0].name: Invalid value: \"fake-container\": Expected value: \"test-container\"\n    spec.containers[0].image: Invalid value: \"fake-image\": Expected value: \"test-image\"]"}

```
```
            	            	actual  : []string{"ASSERT: [RUNNING...]", "ASSERT: [ERROR\nresource test-pod doesn't match expectation:\n    spec.containers[0].image: Invalid value: \"fake-image\": Expected value: \"test-image\"\n    spec.containers[0].name: Invalid value: \"fake-container\": Expected value: \"test-container\"]"}
```

**Comment by shubham-cmyk** [comment]
@eddycharly Actually This was happening to me also. This didn't happen when I tested it locally

**Pull request merged**
