### PR TITLE
Update bindings.md with 'x_k8s_get()' example

### LINKED ISSUE #1897: [Question] Can an entire resource be a valid binding value?
### Describe your question

Hello, and thank you for Chainsaw! It's powerful and has loads of potential.
I've been starting to use it for some assertions, to make sure that our Crossplane resources pass muster.

**Question:** Is it possible/viable to bind an entire resource, for later reference in an assertion?

These are the relevant lines from my `chainsaw-test.yaml` file:

```yaml
---
# yaml-language-server: $schema=https://github.com/kyverno/chainsaw/raw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test

metadata:
  name: xrd

spec:
  steps:
    - name: Bind XRD to check against Compositions
      try:
        - assert:
            bindings:
              - name: xrd
                value:
                  resource:
                    apiVersion: apiextensions.crossplane.io/v1
                    kind: CompositeResourceDefinition
                    metadata:
                      name: crossplane-xrd
            resource:
              apiVersion: apiextensions.crossplane.io/v1
              kind: Composition
              metadata:
                name: crossplane-composition
              spec:
                compositeTypeRef:
                  apiVersion:
                    (ends_with(@, '/v1alpha1')): true
                    (ends_with(@, '/v1alpha2')): false
                    ## Uncommenting this assertion gives an error.
                    # (ends_with(@, $xrd.versions[?referenceable].name)): true
```

When I add `xrd` in the `bindings` list and give the `value` as a `resource` object, Chainsaw doesn't seem to have any issues with that syntax.
I could absolutely see this part being a gap in the implementation, though.

If I uncomment the last assertion on the bottom line, I get the below error:

```
spec.compositeTypeRef.apiVersion.(ends_with(@, $xrd.versions[?referenceable].name)): Internal error: invalid type for: <nil>, expected: []functions.JpType{"string"}
```

### chainsaw version Version

v0.2.8

### Additional context

I would like to be able to check the `.spec.compositeTypeRef.apiVersion` field of all relevant `Composition`-type resources.
I want the version on the end of the `apiVersion` string field to match the version from the XRD that has `referenceable: true` set.

There is #1034 about a `lookup` operation and I thought this could be similar, or maybe the existing `get` operation can cover off this use case, and wanted to ask for clarity's sake.
More generally, being able to bind (or `lookup` or `get`) one or more specific resources and refer to them in assertions against other resources would be fantastic.

### PR DESCRIPTION
**Pull request by jlucktay**
## Explanation

Added a commented example on how to bind other objects with the `x_k8s_get()` function, then refer and assert against.

## Related issue

Resolves #1897.

## Proposed Changes

Documentation only, with an example test and contextual comments.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
- [ ] This is a bug fix and I have added unit tests that prove my fix is effective.

## Further Comments

There is currently no documentation anywhere that I could find to describe how the `x_k8s_get()` function behaves, or what inputs it would take.

### CODE REVIEW

**Comment by jlucktay** [comment]
Yes, of course, we can split it up and rearrange however you see fit.

I just wanted to capture some working samples for this functionality, because I think it's yet another example of how powerful Chainsaw can be. 💪

**Comment by jlucktay** [comment]
@eddycharly I moved the code sample to its own page, and pointed a couple of links there. Is that structure OK?

**Comment by eddycharly** [comment]
@jlucktay you can't really do that in the functions reference docs, it is a generated page.

Can I push in your PR ?

**Comment by jlucktay** [comment]
> Can I push in your PR ?

Sure, please go ahead. 
I don't really have any context on the tooling used for generating and maintaining these docs, and am glad to defer to someone who does.

**Comment by eddycharly** [comment]
Ok, let's do that, thanks!

**Review by eddycharly — APPROVED** [review]
Thanks @jlucktay for initiating this change !

**Pull request merged**
