### PR TITLE
Added a structured content to community section of chainsaw website

### LINKED ISSUE #1314: Add more in the Community section of the website
We can take inspiration from:
https://squidfunk.github.io/mkdocs-material/contributing/

### PR DESCRIPTION
**Pull request by Manoramsharma**
## Explanation

This PR is aligned towards adding a more structured and providing a detailed information under the community section of the chainsaw website including the instructions about the reporting a bug, making a pull request, requesting changes, adding translations to the present documentation. These changes will definitely help the community to grow making the new contributors more aware about the guidelines for engaging to the project. 

## Related issue

Fixes #1314 

## Proposed Changes

I have made a dedicated structure under the communiy section of the chainsaw website , already tested in my local. Attaching the ss of the same you can have a look. @eddycharly 

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
- [x] This is a bug fix and I have added unit tests that prove my fix is effective.
Screenshot 2024-07-02 at 12 51 35 PM
Screenshot 2024-07-02 at 12 52 35 PM

### CODE REVIEW

**Comment by eddycharly** [comment]
This looks great 🙏 

One note though, i'm not sure translations is relevant in our case 🤔

**Comment by eddycharly** [comment]
@Manoramsharma i removed the translations part

**Review by eddycharly — APPROVED** [review]

**Comment by eddycharly** [comment]
LGTM ! Thanks 🙏

**Comment by Manoramsharma** [comment]
> @Manoramsharma i removed the translations part

That's okay, I was planning to add chainsaw specific things to the section and wanted to discuss the same with you like translations part, code of conduct and other things that I kept general for now. I think you can look up to these and ask me to add anything you find relevant at any point of time. 😄

**Pull request merged**
